#!/bin/bash


if [ "$(id -u)" != "0" ]; then
   echo "Script must be run as root !"
   exit 0
fi

. params.sh
. func.sh

echo ""
date
echo "**********************************************"
echo "* Extracting structure of OpenELEC SD Card   *"
echo "* and copying partitions data to directories *"
echo "**********************************************"
echo ""


check_sdcard "nocreate"
if [ $? -ne 0 ]; then
	exit $?
fi


umount ${sdcard}* > /dev/null 2>&1
sleep 1

mkdir -p ${bkpdir}/openELECimg > /dev/null 2>&1

#=======================================================================

# Calculate partitions offsets and sizes
echo ""
echo "Analyzing sd card ..."
sdcard_part=`fdisk -l $sdcard | grep Linux | awk '{print $1}'`
sdcard_sect=`fdisk -l $sdcard | grep "Disk $sdcard" | awk '{print $7}'`
if [ "${sdcard_sect}" = "" ]; then
    sdcard_sect=`fdisk -l $sdcard | grep total | awk '{print $8}'`
fi
sdcard_end=$(expr $sdcard_sect - 1024)

fat=`fdisk -l $sdcard | grep FAT`
if [ "${fat}" = "" ]; then
  linuxpart="1"
else
  linuxpart="2"
fi

if [ "${linuxpart}" = "2" ]; then
	fat_start=`fdisk -l $sdcard | grep ${sdcard}1 | awk '{print $2}'`
	fat_end=`fdisk -l $sdcard | grep ${sdcard}1 | awk '{print $3}'`
	fat_size=$(( ($fat_end - $fat_start + 1) / 2048 ))
	linux_start=`fdisk -l $sdcard | grep ${sdcard}2 | awk '{print $2}'`
	linux_end=`fdisk -l $sdcard | grep ${sdcard}2 | awk '{print $3}'`
	linux_size=$(( ($linux_end - $linux_start + 1) / 2048 ))
else
	linux_start=`fdisk -l $sdcard | grep ${sdcard}1 | awk '{print $2}'`
	linux_end=`fdisk -l $sdcard | grep ${sdcard}1 | awk '{print $3}'`
	linux_size=$(( ($linux_end - $linux_start + 1) / 2048 ))
fi

echo ""
echo "  SDCard size: $sdcard_sect blocks, $(expr $sdcard_sect / 2048 ) M"
echo "------------------------------------------------"
if [ "${linuxpart}" = "2" ]; then
	printf "%14s" "FAT part:"; printf "%12s" $fat_start; printf "%12s" $fat_end; printf "%10s\n" "$fat_size M"
fi
	printf "%14s" "ext4 part:"; printf "%12s" $linux_start; printf "%12s" $linux_end; printf "%10s\n" "$linux_size M"
echo "------------------------------------------------"
echo ""


if [ "${linuxpart}" = "2" ]; then
	if [ "${fat_start}" = "" ] || [ "${linux_start}" = "" ]; then
		echo "Bad SDCard partition structure !"
		exit 1
	fi
	if [ ! "${fat_start}" = "4096" ]; then
		echo "Bad SDCard partition structure (start) !"
		exit 1
	fi
else
	if [ "${linux_start}" = "" ]; then
		echo "Bad SDCard partition structure !"
		exit 1
	fi
	if [ ! "${linux_start}" = "4096" ]; then
		echo "Bad SDCard partition structure (start)!"
		exit 1
	fi
	echo "SDCard is ext4 only card!"
fi

mkdir _mnt > /dev/null 2>&1
umount _mnt > /dev/null 2>&1
mkdir _mnt1 > /dev/null 2>&1
umount _mnt1 > /dev/null 2>&1

echo ""
echo -n "WARNING: OpenElec files in $bkpdir/openELECimg WILL BE UPDATED !, Continue (y/N)?  "
read -n 1 ANSWER

if [ ! "${ANSWER}" = "y" ] ; then
    echo "."
    echo "Canceled.."
    exit 0
fi
echo ""

# EXTRACTING FILES

echo ""
if [ "${_isimage}" = "yes" ]; then
	kpartx -l ${sdcard} > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "ERROR testing kpartx"
		exit 1
	fi
	loop_dev=`kpartx -l $sdcard | grep 4096 | sed s/"\// "/g | awk '{print $6}'`

	kpartx -a -s ${sdcard} > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "ERROR mounting with kpartx"
		exit 1
	fi
        sleep 1
	if [ "${linuxpart}" = "2" ]; then
		mkdir ${bkpdir}/openELECimg/System > /dev/null 2>&1
		loop_mapp="/dev/mapper/${loop_dev}p1"
		mount ${loop_mapp} _mnt > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			echo "ERROR mounting ${loop_mapp}"
			kpartx -d -s ${sdcard} > /dev/null 2>&1
			dmsetup remove /dev/mapper/${loop_dev}p* > /dev/null 2>&1
			losetup -d /dev/${loop_dev} > /dev/null 2>&1
			exit 1
		fi
		echo "Copying FAT (System) partition ..."
		rsync -r -t -p -o -g -x --delete -l -H -D --numeric-ids -s --stats _mnt/ ${bkpdir}/openELECimg/System/ > /dev/null 2>&1
		sync
		fs_size=`du -s -h ${bkpdir}/openELECimg/System | awk '{print $1}'`
		echo "File system size: $fs_size"
		umount _mnt
	fi
	loop_mapp="/dev/mapper/${loop_dev}p${linuxpart}"
	mkdir ${bkpdir}/openELECimg/Storage > /dev/null 2>&1
		mount ${loop_mapp} _mnt > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			echo "ERROR mounting ${loop_mapp}"
			kpartx -d -s ${sdcard} > /dev/null 2>&1
			dmsetup remove /dev/mapper/${loop_dev}p* > /dev/null 2>&1
			losetup -d /dev/${loop_dev} > /dev/null 2>&1
			exit 1
		fi
	echo ""
	echo "Copying ext4 (Storage) partition ..."
	rsync -r -t -p -o -g -x --delete -l -H -D --numeric-ids -s --stats _mnt/ ${bkpdir}/openELECimg/Storage/ > /dev/null 2>&1
	sync
	fs_size=`du -s -h ${bkpdir}/openELECimg/Storage | awk '{print $1}'`
	echo "File system size: $fs_size"

	sleep 2
	umount _mnt > /dev/null 2>&1
	kpartx -d -s ${sdcard} > /dev/null 2>&1
	sleep 1
	if [ $? -ne 0 ]; then
		echo "WARNING: ERROR unmounting with kpartx"
	fi
	dmsetup remove /dev/mapper/${loop_dev}p* > /dev/null 2>&1
	losetup -d /dev/${loop_dev} > /dev/null 2>&1
else
	if [ "${linuxpart}" = "2" ]; then
		mkdir ${bkpdir}/openELECimg/System > /dev/null 2>&1
		mount ${sdcard}1 _mnt > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			echo "ERROR mounting ${sdcard}2"
			exit 1
		fi
		echo "Copying FAT (System) partition ..."
		rsync -r -t -p -o -g -x --delete -l -H -D --numeric-ids -s --stats _mnt/ ${bkpdir}/openELECimg/System/ > /dev/null 2>&1
		sync
		fs_size=`du -s -h ${bkpdir}/openELECimg/System | awk '{print $1}'`
		echo "File system size: $fs_size"
		umount _mnt
	fi
	mkdir ${bkpdir}/openELECimg/Storage > /dev/null 2>&1
	mount ${sdcard}${linuxpart} _mnt > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "ERROR mounting ${sdcard}${linuxpart}"
		exit 1
	fi
	echo ""
	echo "Copying ext4 (Storage) partition ..."
	rsync -r -t -p -o -g -x --delete -l -H -D --numeric-ids -s --stats _mnt/ ${bkpdir}/openELECimg/Storage/ > /dev/null 2>&1
	sync
	fs_size=`du -s -h ${bkpdir}/openELECimg/Storage | awk '{print $1}'`
	echo "File system size: $fs_size"
	umount _mnt
fi


echo ""
echo "Preparing OpenELEC for multi boot..."

cd ${bkpdir}/openELECimg/System
if [ ! -f INITRD ]; then
    echo "INITRD not found."
    exit 1
fi

cp INITRD INITRD.orig

dd if=INITRD of=initrd.oelec bs=64 skip=1 > /dev/null 2>&1
mkdir init > /dev/null 2>&1
rm initrd.new > /dev/null 2>&1
rm INITRD > /dev/null 2>&1

cd init
cpio -i < ../initrd.oelec > /dev/null 2>&1

if [ ! -f platform_init ]; then
    echo "platform_init not found."
    exit 1
fi

echo "" >> platform_init
echo "mkdir /mnt" >> platform_init
echo "mount /dev/mmcblk0p1 /mnt" >> platform_init
echo "cp /mnt/bootsel.ini /mnt/boot.ini" >> platform_init
echo "umount /mnt" >> platform_init
echo "rmdir /mnt" >> platform_init

find | cpio -H newc -o > ../initrd.new
cd ..
mkimage -A arm -O linux -T ramdisk -C none -a 0 -e 0 -n "RootFS [Odroid]" -d initrd.new INITRD
rm initrd.new > /dev/null 2>&1

sync
echo "OK."
echo ""

echo "=================================="
echo "OpenEELEC prepared for multi boot."
echo "=================================="
echo ""
# -------------------------------------------------------------------
